import { drillContracts } from './drill-contracts';

export type Drill = {
  id: string; title: string; track: string; minutes: number; seed: number;
  goal: string; dataset: string; task: string; expected: string;
  starter: string; metric: string; start: number; end: number;
};

const starter = (body: string) => `# Seeded ML Drills — edit only the TODO line\nimport torch\nSEED = __SEED__\ntorch.manual_seed(SEED)\n\n${body}\n# TODO: write one line below\n`;

export const drills: Drill[] = [
  ['tensor-shapes','Read tensor shapes','Tensor basics',6,11,'Find the batch and feature dimensions.','8 samples × 3 features','Return the shape of x.','(8, 3)',['x.shape','tuple(x.size())','x.size()'],starter('x = torch.tensor([[0.1, 0.2, 0.3]] * 8)'),'shape',0,1],
  ['broadcast-bias','Add a broadcast bias','Tensor basics',7,23,'Use a vector bias across a batch.','4 samples × 2 features','Add bias to x without a loop.','[[1.25, -0.5], ...]',['x + bias','x+bias'],starter('x = torch.tensor([[1.0, -1.0]] * 4)\nbias = torch.tensor([0.25, 0.5])'),'mean',0.12,0.75],
  ['seeded-shuffle','Shuffle with a seed','Tensor basics',6,41,'Make the same shuffled order twice.','12 row index set','Create a seeded permutation.','[11, 7, 2, 4, ...]',['torch.randperm','manual_seed'],starter('SEED = 41\nrows = torch.arange(12)'),'first index',0,11],
  ['split-indices','Make train and validation splits','Data handling',8,7,'Keep rows apart while preserving a fixed split.','20 labeled points','Select the first 16 shuffled rows for training.','16 train / 4 validation rows',['perm[:16]','permutation[:16]'],starter('SEED = 7\nperm = torch.randperm(20)'),'train rows',0,16],
  ['standardize','Standardize one feature','Data handling',8,19,'Center and scale a column from training values.','10 height values','Compute z scores from x.','mean ≈ 0.00, std ≈ 1.00',['(x - x.mean()) / x.std()','(x-x.mean())/x.std()'],starter('x = torch.tensor([2., 3., 5., 5., 8., 13., 21., 34., 55., 89.])'),'std',2.3,1],
  ['one-hot','Encode class labels','Data handling',7,29,'Turn labels into model-ready columns.','6 labels, 3 classes','One-hot encode y with 3 classes.','6 × 3 tensor',['torch.nn.functional.one_hot','F.one_hot'],starter('y = torch.tensor([0, 2, 1, 0, 2, 1])'),'columns',0,3],
  ['linear-forward','Write a linear forward pass','Linear models',8,31,'Map two features to one prediction.','5 samples × 2 features','Compute x @ w + b.','5 predictions',['x @ w + b','x@w+b'],starter('x = torch.tensor([[1., 2.]] * 5)\nw = torch.tensor([0.4, -0.1])\nb = 0.2'),'prediction',0,0.4],
  ['mse-loss','Measure squared error','Linear models',7,37,'Measure how far predictions miss targets.','4 prediction/target pairs','Compute mean squared error.','0.025',['((pred - y) ** 2).mean()','((pred-y)**2).mean()','F.mse_loss'],starter('pred = torch.tensor([0.2, 0.8, 0.4, 0.9])\ny = torch.tensor([0., 1., 0.5, 1.])'),'MSE',1,0.025],
  ['gradient-step','Take one gradient step','Linear models',10,43,'Update a scalar weight using its gradient.','6 regression pairs','Subtract lr times w.grad.','loss decreases after one step',['w -= lr * w.grad','w-=lr*w.grad'],starter('w = torch.tensor(0.0, requires_grad=True)\nlr = 0.1\n# loss.backward() already ran'),'loss',1.2,0.54],
  ['logit','Compute a binary logit','Classification',7,47,'Build the score before sigmoid.','4 samples × 2 features','Compute x @ w + b.','4 logits',['x @ w + b','x@w+b'],starter('x = torch.tensor([[1., -1.]] * 4)\nw = torch.tensor([0.8, -0.3])\nb = -0.1'),'logit',0,1],
  ['sigmoid','Turn logits into probabilities','Classification',6,53,'Map a logit to a probability.','5 fixed logits','Apply sigmoid to logits.','values between 0 and 1',['torch.sigmoid','sigmoid('],starter('logits = torch.tensor([-2., -1., 0., 1., 2.])'),'probability',0,0.5],
  ['threshold','Choose class labels','Classification',6,59,'Turn probabilities into a clear decision.','8 probability values','Predict 1 where p is at least 0.5.','[0, 1, 1, ...]',['p >= 0.5','p>=0.5'],starter('p = torch.tensor([0.12, 0.51, 0.92, 0.49, 0.76, 0.32, 0.50, 0.08])'),'positive rate',0,0.5],
  ['bce','Use binary cross entropy','Classification',9,61,'Train from logits without losing precision.','6 logits and labels','Use binary_cross_entropy_with_logits.','loss ≈ 0.26',['binary_cross_entropy_with_logits','BCEWithLogitsLoss'],starter('logits = torch.tensor([-1.2, 1.4, 0.8, -0.7, 2.0, -1.5])\ny = torch.tensor([0., 1., 1., 0., 1., 0.])'),'BCE',1,0.255],
  ['accuracy','Compute accuracy','Classification',6,67,'Count correct class decisions.','10 predictions and labels','Take the mean of pred == y.','0.80',['(pred == y).float().mean()','(pred==y).float().mean()'],'pred = torch.tensor([1,0,1,1,0,1,0,1,0,1])\ny = torch.tensor([1,0,0,1,0,1,0,1,1,1])\n# TODO: write one line below','accuracy',0,0.8],
  ['relu','Apply a ReLU layer','Networks',6,71,'Keep positive activations and clip negatives.','6 pre-activations','Apply relu to z.','[0, 0, 0.4, ...]',['torch.relu','F.relu','relu('],starter('z = torch.tensor([-2., -0.1, 0.4, 1.2, -0.7, 0.])'),'active units',0,3],
  ['two-layer','Connect two linear layers','Networks',10,73,'Build a small non-linear prediction.','3 samples × 2 features','Apply ReLU between both layers.','3 outputs',['torch.relu','@ w1','@w1'],starter('x = torch.tensor([[1., 0.5]] * 3)\nw1 = torch.ones((2, 3))\nw2 = torch.ones((3, 1))'),'output',0,4.5],
  ['dropout-mode','Switch dropout off for evaluation','Networks',7,79,'Make repeated evaluation predictions stable.','Tiny dropout network','Set the model to evaluation mode.','two runs match',['model.eval()','net.eval()'],starter('model = torch.nn.Sequential(torch.nn.Dropout(0.5))'),'variance',1,0],
  ['batch-loss','Average a batch loss','Training loops',7,83,'Combine per-example losses fairly.','8 per-example losses','Take the mean loss.','one scalar',['losses.mean()','loss.mean()'],starter('losses = torch.tensor([0.4, 0.6, 0.2, 0.3, 0.5, 0.1, 0.7, 0.2])'),'loss',1,0.375],
  ['zero-grad','Clear old gradients','Training loops',6,89,'Avoid adding yesterday’s gradient to this step.','One SGD optimizer','Clear gradients before backward.','gradient is fresh',['optimizer.zero_grad()','optim.zero_grad()'],starter('optimizer = torch.optim.SGD([torch.tensor(1., requires_grad=True)], lr=0.1)'),'gradient',1,0],
  ['epoch-loop','Count training-pass updates','Training loops',8,97,'Count updates across three fixed data passes.','3 batches per epoch','Multiply three epochs by the batch count.','9 batch updates',['3 * len(batches)','len(batches) * 3'],starter('batches = range(3)'),'updates',0,9],
  ['early-stop','Check a validation improvement','Training loops',9,101,'Detect when validation loss improves.','Current and best validation loss','Check whether val_loss is lower than best.','True',['val_loss < best','val_loss<best'],starter('best = float("inf")\nval_loss = 0.38'),'improves',0,1],
  ['confusion','Read a confusion matrix','Evaluation',8,103,'Separate false positives from false negatives.','12 labels and predictions','Count predicted 1 when y is 0.','2 false positives',['((pred == 1) & (y == 0)).sum()'],'pred = torch.tensor([1,0,1,1,0,1,0,1,0,1,0,0])\ny = torch.tensor([1,0,0,1,0,0,0,1,1,1,0,1])\n# TODO: write one line below','false positives',0,2],
  ['precision','Compute precision','Evaluation',7,107,'Ask how many positive predictions were right.','12 binary decisions','Compute TP / (TP + FP).','0.80',['tp / (tp + fp)','tp/(tp+fp)'],starter('tp = torch.tensor(4.)\nfp = torch.tensor(1.)'),'precision',0,0.8],
  ['recall','Compute recall','Evaluation',7,109,'Ask how many real positives were found.','12 binary decisions','Compute TP / (TP + FN).','0.67',['tp / (tp + fn)','tp/(tp+fn)'],starter('tp = torch.tensor(4.)\nfn = torch.tensor(2.)'),'recall',0,0.67],
  ['overfit-gap','Spot an overfitting gap','Evaluation',7,113,'Compare training and validation loss.','6 epoch trace','Subtract validation loss from train loss.','gap = 0.31',['val_loss - train_loss','val_loss-train_loss'],starter('train_loss = 0.21\nval_loss = 0.52'),'gap',0,0.31],
  ['knn-distance','Measure squared distance','Classical ML',8,127,'Find the nearest known point.','5 two-dimensional points','Sum squared coordinate differences.','nearest index = 2',['((x - q) ** 2).sum','((x-q)**2).sum'],starter('x = torch.tensor([[0.,0.],[1.,1.],[2.,2.],[3.,3.],[4.,4.]])\nq = torch.tensor([2.1, 2.2])'),'nearest',0,2],
  ['kmeans-centroid','Update a centroid','Classical ML',7,131,'Move a centroid to its assigned points.','4 assigned points','Take the mean over points.','[2.5, 2.5]',['points.mean(dim=0)','points.mean(0)'],starter('points = torch.tensor([[2.,2.],[2.,3.],[3.,2.],[3.,3.]])'),'centroid',0,2.5],
  ['pca-center','Center data before PCA','Classical ML',7,137,'Remove the mean before finding directions.','6 points × 2 features','Subtract the column mean.','column means = 0',['x - x.mean(dim=0)','x-x.mean(dim=0)'],starter('x = torch.tensor([[1.,2.],[2.,3.],[3.,4.],[4.,5.],[5.,6.],[6.,7.]])'),'mean',3.5,0],
  ['replay-seed','Replay a run from its seed','Reproducibility',6,149,'Prove a result can be made again.','Seeded XOR data','Set the documented seed.','same trace twice',['torch.manual_seed(SEED)','manual_seed(SEED)'],starter('SEED = 149'),'trace difference',1,0],
  ['save-config','Record training settings','Reproducibility',6,151,'Keep the settings needed to repeat a run.','Seed, learning rate, epochs','Create a config dictionary.','three saved fields',['{"seed": SEED','{"seed":SEED','dict(seed=SEED)'],starter('SEED = 151\nlr = 0.03\nepochs = 8'),'saved fields',0,3]
].map(([id,title,track,minutes,seed,goal,dataset,task,expected,_legacyExamples,starter,metric,start,end]) => ({ id,title,track,minutes,seed,goal,dataset,task,expected,starter: (starter as string).replace('__SEED__', String(seed)),metric,start,end } as Drill));

export const tracks = [...new Set(drills.map((drill) => drill.track))];

if (drills.some((drill) => !drillContracts[drill.id]) || Object.keys(drillContracts).length !== drills.length) {
  throw new Error('Every drill must have exactly one evaluator contract.');
}
